/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zeki
 */
public class HesapAyarlariForm extends javax.swing.JFrame {

    /**
     * Creates new form HesapAyarlariForm
     */
    public HesapAyarlariForm() {
        initComponents();
        dataGetir();
        btnSil.setEnabled(false);
        btnDuzenle.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKadi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSifre = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtSifreTekrar = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cbYetki = new javax.swing.JComboBox<>();
        btnKaydet = new javax.swing.JButton();
        btnDuzenle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHesaplar = new javax.swing.JTable();
        btnSil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ZSG | Cari Hesap Programı - Hesap İşlemleri");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kullanıcı Ayarları"));

        jLabel1.setText("Kullanıcı Adı :");

        jLabel2.setText("Şifre :");

        jLabel3.setText("Şifre Tekrar : ");

        jLabel4.setText("Yetki :");

        cbYetki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Satış Görevlisi", "Muhasebeci", "Mağza Müdürü" }));

        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        btnDuzenle.setText("Düzenle");
        btnDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuzenleActionPerformed(evt);
            }
        });

        tblHesaplar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHesaplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHesaplarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHesaplar);

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDuzenle)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSil)
                        .addGap(18, 18, 18)
                        .addComponent(btnKaydet))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSifre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSifreTekrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKadi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbYetki, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbYetki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKaydet)
                    .addComponent(btnDuzenle)
                    .addComponent(btnSil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        String kAdi = txtKadi.getText().trim();
        String kSifre1 = txtSifre.getText();
        String kSifre2 = txtSifreTekrar.getText();
        int yetki = cbYetki.getSelectedIndex();

        if (kAdi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Kullanıcı adı girin...");
            txtKadi.requestFocus();
        } else if (kSifre1.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "şifre girin...");
            txtSifre.requestFocus();
        } else if (kSifre2.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "şifre tekrar girin...");
            txtSifre.requestFocus();
        }
        if (kSifre1.equals(kSifre2)) {
            try {
                System.out.println(yetki);
                String kaydetQuery = "insert into kullanicilar values(null,'" + kAdi + "','" + kSifre1 + "','" + yetki + "')";
                int sonuc = db.baglan().executeUpdate(kaydetQuery);
                if (sonuc > 0) {
                    txtKadi.setText("");
                    txtSifre.setText("");
                    txtSifreTekrar.setText("");

                    JOptionPane.showMessageDialog(rootPane, "Kayıt Başarılı");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Kayıt Başarısız");

                }
            } catch (Exception e) {
                System.err.println("kaydetme hatası : " + e);
                if (e.toString().contains("SQLITE_CONSTRAINT_UNIQUE")) {
                    JOptionPane.showMessageDialog(rootPane, "Bu kullanıcı adı zaten var...");
                }
            } finally {
                db.dbKapat();
                dataGetir();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Şifreler aynı olmalı");
            txtSifre.requestFocus();
        }

    }//GEN-LAST:event_btnKaydetActionPerformed
    String kdAdi;
    private void tblHesaplarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHesaplarMouseClicked
        int row = tblHesaplar.getSelectedRow();
        if (row > -1) {
            kdAdi = (String) tblHesaplar.getValueAt(row, 0);
            txtKadi.setText(kdAdi);
            btnSil.setEnabled(true);
            btnDuzenle.setEnabled(true);
            btnKaydet.setEnabled(false);
        }
    }//GEN-LAST:event_tblHesaplarMouseClicked

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed

        try {
            String silQuery = "delete from kullanicilar where kAdi = '" + kdAdi + "' ";
            int silSonuc = db.baglan().executeUpdate(silQuery);
            if (silSonuc > 0) {
                db.dbKapat();
                dataGetir();
                JOptionPane.showMessageDialog(rootPane, "Silme işlemi başarılı");
                txtKadi.setText("");
                txtSifre.setText("");
                txtSifreTekrar.setText("");
                btnSil.setEnabled(false);
                btnDuzenle.setEnabled(false);
                btnKaydet.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Silme hatası !");
            }
        } catch (Exception e) {
            System.err.println("Silme hatası : " + e);
        } finally {
            db.dbKapat();

        }
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuzenleActionPerformed
        String kAdi = txtKadi.getText().trim();
        String kSifre1 = txtSifre.getText();
        String kSifre2 = txtSifreTekrar.getText();
        int yetki = cbYetki.getSelectedIndex();

        if (kAdi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Kullanıcı adı girin...");
            txtKadi.requestFocus();
        } else if (kSifre1.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "şifre girin...");
            txtSifre.requestFocus();
        } else if (kSifre2.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "şifre tekrar girin...");
            txtSifre.requestFocus();
        } else {
            if (kSifre1.equals(kSifre2) && !kSifre1.equals("")) {
                try {
                    String duzenleQuery = "update kullanicilar set kAdi = '" + kAdi + "', "
                            + "kSifre = '" + kSifre1 + "', kErisim = '" + yetki + "' where kAdi = '" + kdAdi + "'";
                    int sonuc = db.baglan().executeUpdate(duzenleQuery);
                    if (sonuc > 0) {
                        txtKadi.setText("");
                        txtSifre.setText("");
                        txtSifreTekrar.setText("");

                        JOptionPane.showMessageDialog(rootPane, "Kayıt Başarılı");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Kayıt Başarısız");

                    }

                } catch (SQLException ex) {
                    System.err.println("Yazma Hatası : " + ex);

                } finally {
                    db.dbKapat();
                }
                dataGetir();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Şifreler aynı olmalı");
                txtSifre.requestFocus();
            }
        }
    }//GEN-LAST:event_btnDuzenleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HesapAyarlariForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HesapAyarlariForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HesapAyarlariForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HesapAyarlariForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HesapAyarlariForm().setVisible(true);
            }
        });
    }
    DBConnection db = new DBConnection();

    public void dataGetir() {
        try {
            String urunlerQuery = "select *from kullanicilar";

            ResultSet rs = db.baglan().executeQuery(urunlerQuery);

            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Kullanici Adi");
            dtm.addColumn("Sifre");
            dtm.addColumn("Yetki");

            while (rs.next()) {
                int yetkiDuzenle = Integer.parseInt(rs.getString("kErisim"));
                String yetki;

                if (yetkiDuzenle == 2) {
                    yetki = "Mağza Müdürü";
                } else if (yetkiDuzenle == 1) {
                    yetki = "Muhasebeci";
                } else {
                    yetki = "Satış görevlisi";
                }
                dtm.addRow(new String[]{rs.getString("kAdi"), rs.getString("kSifre"), yetki});
            }
            tblHesaplar.setModel(dtm);

        } catch (Exception e) {
            System.err.println("okuma hatası...");
        } finally {
            db.dbKapat();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDuzenle;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnSil;
    private javax.swing.JComboBox<String> cbYetki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHesaplar;
    private javax.swing.JTextField txtKadi;
    private javax.swing.JPasswordField txtSifre;
    private javax.swing.JPasswordField txtSifreTekrar;
    // End of variables declaration//GEN-END:variables
}
