/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zeki
 */
public class SatisYonetimi extends javax.swing.JFrame {

    /**
     * Creates new form SatisYonetimi
     */
    static DBConnection db = new DBConnection();

    int id = -1;

    public SatisYonetimi(int id) {

        System.out.println("satis yonetimi ids: " + id);
        this.id = id;
        initComponents();
        musteriBilgisi(id);
        UrunGetir();
        dataGetir();
        btnEkle.setEnabled(false);
        btnSatisTamamla.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMusteriAdSoyad = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMusteriBakiye = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtAra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusteriler = new javax.swing.JTable();
        btnMusteriAra = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtUrunAra = new javax.swing.JTextField();
        btnUrunAra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUrunler = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnSatisTamamla = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblPesinat = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblSatisToplam = new javax.swing.JLabel();
        lblPesinAlinan = new javax.swing.JLabel();
        lblKalanBakiye = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblUrunKodu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblUrunAdi = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPesinAlinan = new javax.swing.JTextField();
        txtMiktar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblBirimFiyati = new javax.swing.JLabel();
        cbTamamiPesin = new javax.swing.JCheckBox();
        txtIskonto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnEkle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ZSG | Cari Hesap Programı - Satış Yönetimi");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Bilgileri"));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Adı  Soyadı :");

        lblMusteriAdSoyad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMusteriAdSoyad.setForeground(new java.awt.Color(0, 0, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Eski Bakiye :");

        lblMusteriBakiye.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMusteriBakiye.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMusteriAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMusteriBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMusteriAdSoyad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblMusteriBakiye))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Bul"));

        jLabel5.setText("Cari Arama : ");

        tblMusteriler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMusteriler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMusterilerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMusteriler);

        btnMusteriAra.setText("Ara");
        btnMusteriAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusteriAraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAra, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMusteriAra))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMusteriAra))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Satış Yap"));

        jLabel6.setText("Stok Adı :");

        btnUrunAra.setText("Ara");

        tblUrunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUrunler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUrunlerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUrunler);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSatisTamamla.setText("Satışı Tamamla");
        btnSatisTamamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatisTamamlaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Kalan Bakiye :");

        lblPesinat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPesinat.setText("Peşinat :");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Toplam :");

        lblSatisToplam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSatisToplam.setText("0.00 TL");

        lblPesinAlinan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPesinAlinan.setText("0.00 TL");

        lblKalanBakiye.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblKalanBakiye.setText("0.00 TL");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSatisToplam))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPesinat)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKalanBakiye)
                            .addComponent(lblPesinAlinan))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblSatisToplam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesinat)
                    .addComponent(lblPesinAlinan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblKalanBakiye))
                .addContainerGap())
        );

        jLabel7.setText("Stok kodu :");

        lblUrunKodu.setText("jLabel14");

        jLabel8.setText("Stok Adı :");

        lblUrunAdi.setText("jLabel15");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Peşin Alınan :");

        txtPesinAlinan.setText("0.00");

        txtMiktar.setText("1");

        jLabel9.setText("Miktar :");

        jLabel10.setText("Fiyat :");

        lblBirimFiyati.setText("jLabel16");

        cbTamamiPesin.setText("Tamamı Peşin Alındı.");

        txtIskonto.setText("0.00");

        jLabel11.setText("İskonto tutarı :");

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblUrunKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(txtMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBirimFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(111, 111, 111)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesinAlinan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbTamamiPesin)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtIskonto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEkle)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUrunAdi)
                    .addComponent(lblUrunKodu)
                    .addComponent(txtMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirimFiyati)
                    .addComponent(txtIskonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtPesinAlinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTamamiPesin)
                    .addComponent(btnEkle))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSatisTamamla, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(btnSatisTamamla)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUrunAra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUrunAra)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUrunAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUrunAra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    ArrayList<Integer> idList = new ArrayList<>();
    ArrayList<Integer> urunIdList = new ArrayList<>();
    private void btnMusteriAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusteriAraActionPerformed
        dataAra();
    }//GEN-LAST:event_btnMusteriAraActionPerformed

    private void tblMusterilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMusterilerMouseClicked
        int row = tblMusteriler.getSelectedRow();
        if (row > -1) {
            kid = idList.get(row);
            islemId = kid;
            musteriBilgisi(kid);
        }
    }//GEN-LAST:event_tblMusterilerMouseClicked
    int uid;
    String urunStok;
    private void tblUrunlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUrunlerMouseClicked
        int row = tblUrunler.getSelectedRow();
        double birimFiyati = 0.0;
        System.out.println("seçim yapildi");
        if (row > -1) {

            urunStok = (String) tblUrunler.getValueAt(row, 4);
            System.out.println("urun stok : " + urunStok);
            uid = urunIdList.get(row);
            lblUrunKodu.setText((String) tblUrunler.getValueAt(row, 0));
            lblUrunAdi.setText((String) tblUrunler.getValueAt(row, 1));
            lblBirimFiyati.setText((String) tblUrunler.getValueAt(row, 6));
            btnEkle.setEnabled(true);
            btnSatisTamamla.setEnabled(true);

        }
    }//GEN-LAST:event_tblUrunlerMouseClicked
    int miktar;
    double pesinat;
    double toplamFiyat;
    double iskonto;
    static int kid;
    int islemId;
    String aIslemTuru = "0";
    String pIslemTuru = "1";

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed

        miktar = Integer.parseInt(txtMiktar.getText());
        iskonto = Double.parseDouble(txtIskonto.getText());
        toplamFiyat = (Double.parseDouble(lblBirimFiyati.getText()) * miktar - iskonto);
        lblSatisToplam.setText(Double.toString(toplamFiyat) + " TL");
        System.out.println(lblSatisToplam.getText());

        if (cbTamamiPesin.isSelected()) {
            double pesinat = toplamFiyat;
            lblPesinAlinan.setText(Double.toString(pesinat) + " TL");
            double kalanBakiye = toplamFiyat - pesinat;
            lblKalanBakiye.setText(Double.toString(kalanBakiye) + " TL");
        } else {
            pesinat = Double.parseDouble(txtPesinAlinan.getText());
            lblPesinAlinan.setText(Double.toString(pesinat) + " TL");
            double kalanBakiye = toplamFiyat - pesinat;
            lblKalanBakiye.setText(Double.toString(kalanBakiye) + " TL");
        }

    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnSatisTamamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatisTamamlaActionPerformed
        DBConnection db1 = new DBConnection();
        DBConnection db2 = new DBConnection();
        DBConnection dbu = new DBConnection();
        try {
            System.out.println("islem yapilcak id" + islemId);
            String kaydetQuery = "insert into satisyonetimi values(null,'" + uid + "','" + miktar + "','" + pesinat + "','" + iskonto + "','" + toplamFiyat + "','" + islemId + "',datetime('now'))";
            String islemKaydet = "insert into Tahsilat values(null,'" + islemId + "','" + aIslemTuru + "','" + toplamFiyat + "',datetime('now'))";
            if (pesinat > 0) {
                String pKaydetQuery = "insert into Tahsilat values(null,'" + islemId + "','" + pIslemTuru + "','" + pesinat + "',datetime('now'))";
                int sonuc3 = db1.baglan().executeUpdate(pKaydetQuery);
                db1.dbKapat();
            }
            int sonuc = db.baglan().executeUpdate(kaydetQuery);
            db.dbKapat();
            int sonuc2 = db2.baglan().executeUpdate(islemKaydet);
            db2.dbKapat();
            
            if (sonuc > 0 && sonuc2 > 0) {
                int toplamStok = (Integer.parseInt(urunStok) - Integer.parseInt(txtMiktar.getText()));
                String duzenleQuery = "update urunler set urunStok ='" + toplamStok + "' where urunId = '" + uid + "'";
                dbu.baglan().executeUpdate(duzenleQuery);
                JOptionPane.showMessageDialog(rootPane, "Satış tamamlandı...");
                

            }

        } catch (SQLException ex) {
            System.err.println("Satış ekleme Hatası : " + ex);

        } finally {
            db.dbKapat();
            db1.dbKapat();
            db2.dbKapat();
            dbu.dbKapat();
            UrunGetir();
        }
    }//GEN-LAST:event_btnSatisTamamlaActionPerformed

    public void dataAra() {
        try {
            String aranan = txtAra.getText();
            String musteriQuery2 = "select *from musteriler where musteriAdi='" + aranan + "' or musteriSoyadi='" + aranan + "' or "
                    + "musteriTelefon='" + aranan + "' ";
            ResultSet rs = db.baglan().executeQuery(musteriQuery2);
            DefaultTableModel dtm = new DefaultTableModel();

            dtm.addColumn("Adı");
            dtm.addColumn("Soyadı");
            dtm.addColumn("Telefon");

            while (rs.next()) {
                idList.add(rs.getInt("musterId"));
                dtm.addRow(new String[]{rs.getString("musteriAdi"), rs.getString("musteriSoyadi"), rs.getString("musteriTelefon")});
            }
            tblMusteriler.setModel(dtm);

        } catch (Exception e) {
            System.err.println("okuma hatası..." + e);
        } finally {
            db.dbKapat();
        }
    }

    public void dataGetir() {
        try {
            String musteriQuery = "select *from musteriler ";
            ResultSet rs = db.baglan().executeQuery(musteriQuery);
            DefaultTableModel dtm = new DefaultTableModel();

            dtm.addColumn("Adı");
            dtm.addColumn("Soyadı");
            dtm.addColumn("Telefon");

            while (rs.next()) {
                idList.add(rs.getInt("musterId"));
                dtm.addRow(new String[]{rs.getString("musteriAdi"), rs.getString("musteriSoyadi"), rs.getString("musteriTelefon")});
            }
            tblMusteriler.setModel(dtm);

        } catch (Exception e) {
            System.err.println("Data okuma hatası..." + e);
        } finally {
            db.dbKapat();
        }
    }

    public void UrunGetir() {
        try {
            String urunlerQuery = "select *from Urunler";

            ResultSet rs = db.baglan().executeQuery(urunlerQuery);

            DefaultTableModel dtm = new DefaultTableModel();

            dtm.addColumn("Barkod");
            dtm.addColumn("Ürün Adı");
            dtm.addColumn("Kategori");
            dtm.addColumn("Marka");
            dtm.addColumn("Stok");
            dtm.addColumn("Alis Fiyati");
            dtm.addColumn("Satış Fiyatı");
            dtm.addColumn("KDV ORANI");

            while (rs.next()) {
                urunIdList.add(rs.getInt("urunId"));
                dtm.addRow(new String[]{rs.getString("urunBarkod"), rs.getString("urunAdi"), rs.getString("urunKategori"), rs.getString("urunMarka"), rs.getString("urunStok"), rs.getString("urunAlisFiyati"),
                    rs.getString("urunSatisFiyati"), rs.getString("urunKDV")});
            }
            tblUrunler.setModel(dtm);

        } catch (Exception e) {
            System.err.println("urun okuma hatası..." + e);
        } finally {
            db.dbKapat();
        }
    }

    public void musteriBilgisi(int id) {
        lblMusteriBakiye.setText("0 TL");
        if (id != -1) {
            DBConnection dbb = new DBConnection();
            DBConnection dbbb = new DBConnection();
            try {
                String q = "select *from musteriler where musterid = '" + id + "'";
                String bakiyeQuery = "select sum(tahsilatTutar) as toplamPesinat from Tahsilat where islemTuru ='1' and kullaniId='" + id + "'";
                String bakiyeQuery2 = "select sum(tahsilatTutar) as toplamSatis from Tahsilat where islemTuru ='0' and kullaniId='" + id + "'";

                ResultSet rs = db.baglan().executeQuery(q);
                ResultSet rsBakiye = dbb.baglan().executeQuery(bakiyeQuery);
                ResultSet rsBakiye2 = dbbb.baglan().executeQuery(bakiyeQuery2);

                if (rs.next()) {
                    String mAdSoyad = rs.getString("musteriadi") + " " + rs.getString("musteriSoyadi");
                    lblMusteriAdSoyad.setText(mAdSoyad);

                }

                if (rsBakiye2.next()) {
                    double tPesinatD = rsBakiye.getString("toplamPesinat") == null ? 0 : rsBakiye.getDouble("toplamPesinat");
                    double sPesinatToplam = tPesinatD;
                    double mBakiye = Double.parseDouble(rsBakiye2.getString("toplamSatis"));
                    double mBakiyeToplam = mBakiye - sPesinatToplam;
                    lblMusteriBakiye.setText(mBakiyeToplam + " TL");
                    System.out.println("Borç var");

                } else {
                    lblMusteriBakiye.setText("");
                }

            } catch (Exception e) {
                System.out.println("musteri bilgisi okuma hatası : " + e);
            } finally {
                db.dbKapat();
                dbb.dbKapat();
                dbbb.dbKapat();
            }
        }
    }

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SatisYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SatisYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SatisYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SatisYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SatisYonetimi(kid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnMusteriAra;
    private javax.swing.JButton btnSatisTamamla;
    private javax.swing.JButton btnUrunAra;
    private javax.swing.JCheckBox cbTamamiPesin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBirimFiyati;
    private javax.swing.JLabel lblKalanBakiye;
    private javax.swing.JLabel lblMusteriAdSoyad;
    private javax.swing.JLabel lblMusteriBakiye;
    private javax.swing.JLabel lblPesinAlinan;
    private javax.swing.JLabel lblPesinat;
    private javax.swing.JLabel lblSatisToplam;
    private javax.swing.JLabel lblUrunAdi;
    private javax.swing.JLabel lblUrunKodu;
    private javax.swing.JTable tblMusteriler;
    private javax.swing.JTable tblUrunler;
    private javax.swing.JTextField txtAra;
    private javax.swing.JTextField txtIskonto;
    private javax.swing.JTextField txtMiktar;
    private javax.swing.JTextField txtPesinAlinan;
    private javax.swing.JTextField txtUrunAra;
    // End of variables declaration//GEN-END:variables
}
