/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zeki
 */
public class UrunYonetimiForm extends javax.swing.JFrame {

    /**
     * Creates new form StokForm
     */
    public UrunYonetimiForm() {
        initComponents();
        dataGetir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUrunler = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtAra = new javax.swing.JTextField();
        btnAra = new javax.swing.JButton();
        btnStokEkle2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBarkod = new javax.swing.JTextField();
        txtUrunAdi = new javax.swing.JTextField();
        txtAlisFiyati = new javax.swing.JTextField();
        txtSatisFiyati = new javax.swing.JTextField();
        cbUrunKategori = new javax.swing.JComboBox<>();
        cbUrunMarka = new javax.swing.JComboBox<>();
        cbKdvOrani = new javax.swing.JComboBox<>();
        cbAlisKdv = new javax.swing.JComboBox<>();
        cbSatisKdv = new javax.swing.JComboBox<>();
        btnKaydet = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnStokEkle = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtStok = new javax.swing.JTextField();
        btnDuzenle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ZSG | Cari Hesap Programı - Ürün Yönetimi");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ürün Yönetimi"));

        tblUrunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUrunler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUrunlerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUrunler);

        jLabel9.setText("Ürün Ara : ");

        txtAra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAraKeyPressed(evt);
            }
        });

        btnAra.setText("ARA");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });

        btnStokEkle2.setText("Stok Ekle");
        btnStokEkle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokEkle2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAra)
                .addGap(18, 18, 18)
                .addComponent(btnStokEkle2, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAra)
                    .addComponent(btnStokEkle2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ürün Ayarları"));
        jPanel2.setToolTipText("");

        jLabel1.setText("Ürün Adı :");

        jLabel2.setText("Kategori :");

        jLabel3.setText("Marka :");

        jLabel4.setText("Stok :");

        jLabel5.setText("Alış Fiyatı :");

        jLabel6.setText("Satış Fiyatı : ");

        jLabel7.setText("KDV Orani  %:");

        jLabel8.setText("Barkod Kodu :");

        txtAlisFiyati.setText("0,00");
        txtAlisFiyati.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAlisFiyatiFocusGained(evt);
            }
        });

        txtSatisFiyati.setText("0,00");
        txtSatisFiyati.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSatisFiyatiFocusGained(evt);
            }
        });

        cbUrunKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbUrunKategoriMouseClicked(evt);
            }
        });
        cbUrunKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUrunKategoriActionPerformed(evt);
            }
        });

        cbUrunMarka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbUrunMarkaMouseClicked(evt);
            }
        });

        cbKdvOrani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        cbAlisKdv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KDV Dahil", "KDV Hariç", " " }));

        cbSatisKdv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KDV Dahil", "KDV Hariç", " " }));

        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnStokEkle.setText("Stok Ekle");
        btnStokEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokEkleActionPerformed(evt);
            }
        });

        jButton7.setText("Ekle");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Ekle");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        txtStok.setText("0");

        btnDuzenle.setText("Düzenlemeyi Kaydet");
        btnDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuzenleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtBarkod, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(txtUrunAdi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbUrunMarka, javax.swing.GroupLayout.Alignment.LEADING, 0, 116, Short.MAX_VALUE)
                            .addComponent(cbUrunKategori, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jButton8))))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(36, 36, 36)
                        .addComponent(txtStok))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbKdvOrani, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSatisFiyati)
                                    .addComponent(txtAlisFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAlisKdv, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSatisKdv, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStokEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(btnDuzenle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBarkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(btnKaydet)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtAlisFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlisKdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDuzenle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbUrunKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtSatisFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSatisKdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(btnSil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbUrunMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbKdvOrani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(btnStokEkle))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    DBConnection db = new DBConnection();
    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        String urunAdi = txtUrunAdi.getText().trim();
        String urunKategori = (String) cbUrunKategori.getSelectedItem();
        String urunMarka = (String) cbUrunMarka.getSelectedItem();
        String urunBarkod = txtBarkod.getText().trim();
        double urunSatisFiyati = Double.parseDouble(txtSatisFiyati.getText());
        double urunAlisFiyati = Double.parseDouble(txtAlisFiyati.getText());
        double urunKdvOrani = cbKdvOrani.getSelectedIndex();
        int urunStok = Integer.parseInt(txtStok.getText());

        if (urunAdi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ürün adı girin...");
            txtUrunAdi.requestFocus();
            txtUrunAdi.setBackground(Color.red);
        } else if (urunBarkod.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Barkod girin...");
            txtBarkod.requestFocus();
        }

        try {
            String kaydetQuery = "insert into urunler values(null,'" + urunBarkod + "','" + urunAdi + "','" + urunKategori + "','" + urunMarka + "',"
                    + "'" + urunStok + "','" + urunAlisFiyati + "','" + urunSatisFiyati + "','" + urunKdvOrani + "')";
            int sonuc = db.baglan().executeUpdate(kaydetQuery);
            if (sonuc > 0) {
                txtUrunAdi.setText("");
                txtBarkod.setText("");
                txtAlisFiyati.setText("0.0");
                txtSatisFiyati.setText("0.0");
                txtStok.setText("0");
                JOptionPane.showMessageDialog(rootPane, "Kayıt Başarılı");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Kayıt Başarısız");

            }
        } catch (Exception e) {
            System.err.println("kaydetme hatası : " + e);
            if (e.toString().contains("SQLITE_CONSTRAINT_UNIQUE")) {
                JOptionPane.showMessageDialog(rootPane, "Bu barkod zaten var...");
            }
        } finally {
            db.dbKapat();
            dataGetir();
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new KategoriForm().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cbUrunKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbUrunKategoriMouseClicked
        cbUrunKategori.removeAllItems();
        cbDoldur();

    }//GEN-LAST:event_cbUrunKategoriMouseClicked

    private void txtAlisFiyatiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlisFiyatiFocusGained
        txtAlisFiyati.setText("");
    }//GEN-LAST:event_txtAlisFiyatiFocusGained

    private void txtSatisFiyatiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSatisFiyatiFocusGained
        txtSatisFiyati.setText("");
    }//GEN-LAST:event_txtSatisFiyatiFocusGained

    private void cbUrunMarkaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbUrunMarkaMouseClicked
        cbUrunMarka.removeAllItems();
        cbDoldur();
    }//GEN-LAST:event_cbUrunMarkaMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new MarkalarForm().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnStokEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokEkleActionPerformed

        new StokForm().setVisible(true);

    }//GEN-LAST:event_btnStokEkleActionPerformed

    private void btnStokEkle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokEkle2ActionPerformed
        new StokForm().setVisible(true);
    }//GEN-LAST:event_btnStokEkle2ActionPerformed

    private void txtAraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAraKeyPressed
        
    }//GEN-LAST:event_txtAraKeyPressed

    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
        dataAra();
    }//GEN-LAST:event_btnAraActionPerformed

    private void cbUrunKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUrunKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUrunKategoriActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        if (ubarkod == -1) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen seçim yapınız");
        } else {
            // silme işlemini yap
            try {
                String silQuery = "delete from urunler where urunBarkod = '" + ubarkod + "' ";
                int silSonuc = db.baglan().executeUpdate(silQuery);
                if (silSonuc > 0) {
                    db.dbKapat();
                    dataGetir();
                    JOptionPane.showMessageDialog(rootPane, "Silme işlemi başarılı");
                    txtBarkod.setText("");
                    txtUrunAdi.setText("");
                    txtSatisFiyati.setText("");
                    txtStok.setText("");
                    txtAlisFiyati.setText("");
                    btnSil.setEnabled(false);
                    btnDuzenle.setEnabled(false);
                    btnKaydet.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Silme hatası !");
                }
            } catch (Exception e) {
                System.err.println("Silme hatası : " + e);
            } finally {
                db.dbKapat();
            }
        }
    }//GEN-LAST:event_btnSilActionPerformed
int ubarkod=-1;
    private void tblUrunlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUrunlerMouseClicked
        int row = tblUrunler.getSelectedRow();
        if (row > -1) {
            ubarkod=Integer.parseInt((String)tblUrunler.getValueAt(row, 0)) ;
            txtBarkod.setText((String) tblUrunler.getValueAt(row, 0));
            txtUrunAdi.setText((String) tblUrunler.getValueAt(row, 1));
            txtAlisFiyati.setText((String) tblUrunler.getValueAt(row, 5));
            txtSatisFiyati.setText((String) tblUrunler.getValueAt(row, 6));
            txtStok.setText((String) tblUrunler.getValueAt(row, 4));
            cbUrunKategori.setSelectedItem(tblUrunler.getValueAt(row, 2));
            btnSil.setEnabled(true);
            btnDuzenle.setEnabled(true);
            btnKaydet.setEnabled(false);
            System.out.println(ubarkod);
            
        }
    }//GEN-LAST:event_tblUrunlerMouseClicked

    private void btnDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuzenleActionPerformed
        String urunAdi = txtUrunAdi.getText().trim();
        String urunKategori = (String) cbUrunKategori.getSelectedItem();
        String urunMarka = (String) cbUrunMarka.getSelectedItem();
        String urunBarkod = txtBarkod.getText().trim();
        double urunSatisFiyati = Double.parseDouble(txtSatisFiyati.getText());
        double urunAlisFiyati = Double.parseDouble(txtAlisFiyati.getText());
        double urunKdvOrani = cbKdvOrani.getSelectedIndex();
        int urunStok = Integer.parseInt(txtStok.getText());

        if (urunAdi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ürün adı girin...");
            txtUrunAdi.requestFocus();
            txtUrunAdi.setBackground(Color.red);
        } else if (urunBarkod.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Barkod girin...");
            txtBarkod.requestFocus();
        }

        try {
            String duzenleQuery = "update urunler set urunBarkod = '" + urunBarkod + "', "
                    + "urunAdi = '" + urunAdi + "', urunkategori = '" + urunKategori + "', "
                    + "urunMarka = '" + urunMarka + "',urunStok ='" + urunStok + "',urunAlisFiyati ='"+urunAlisFiyati+"'"
                    + ",urunSatisFiyati = '"+urunSatisFiyati+"',urunKDV='"+urunKdvOrani+"' where urunBarkod = '" + ubarkod + "'";
            int sonuc = db.baglan().executeUpdate(duzenleQuery);
            if (sonuc > 0) {
                txtUrunAdi.setText("");
                txtBarkod.setText("");
                txtAlisFiyati.setText("0.0");
                txtSatisFiyati.setText("0.0");
                txtStok.setText("0");
                JOptionPane.showMessageDialog(rootPane, "Kayıt Başarılı");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Kayıt Başarısız");

            }

        } catch (SQLException ex) {
            System.err.println("Yazma Hatası : " + ex);

        } finally {
            db.dbKapat();
        }
        dataGetir();
    }//GEN-LAST:event_btnDuzenleActionPerformed
    public void cbDoldur() {
        try {
            String kategoriQuery = "select kategoriAdi from Kategoriler";
            String markaQuery = "select markaAdi from markalar";

            ResultSet rsKategoriler = db.baglan().executeQuery(kategoriQuery);
            ResultSet rsMarkalar = db.baglan().executeQuery(markaQuery);

            while (rsKategoriler.next()) {
                cbUrunKategori.addItem(rsKategoriler.getString(1));
            }

            while (rsMarkalar.next()) {
                cbUrunMarka.addItem(rsMarkalar.getString(1));
            }
        } catch (Exception e) {
            System.err.println("Veri tabanı getirme hatası:" + e);
        } finally {
            db.dbKapat();
        }
    }

    public void dataGetir() {
        try {
            String urunlerQuery = "select *from urunler";

            ResultSet rs = db.baglan().executeQuery(urunlerQuery);

            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Barkod");
            dtm.addColumn("Ürün Adı");
            dtm.addColumn("Kategori");
            dtm.addColumn("Marka");
            dtm.addColumn("Stok");
            dtm.addColumn("Alis Fiyati");
            dtm.addColumn("Satış Fiyatı");
            dtm.addColumn("KDV ORANI");

            while (rs.next()) {
                dtm.addRow(new String[]{rs.getString("urunBarkod"), rs.getString("urunAdi"), rs.getString("urunKategori"), rs.getString("urunMarka"), rs.getString("urunStok"), rs.getString("urunAlisFiyati"),
                    rs.getString("urunSatisFiyati"), rs.getString("urunKDV")});
            }
            tblUrunler.setModel(dtm);

        } catch (Exception e) {
            System.err.println("okuma hatası...");
        } finally {
            db.dbKapat();
        }
    }
    String aranan="";
     public void dataAra() {
        try {
            aranan = txtAra.getText();
            String urunlerQuery = "select *from urunler where urunbarkod='"+aranan+"'"
                    + "or urunAdi='"+aranan+"' or urunKategori = '"+aranan+"' or urunMarka='"+aranan+"'";

            ResultSet rs = db.baglan().executeQuery(urunlerQuery);

            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Barkod");
            dtm.addColumn("Ürün Adı");
            dtm.addColumn("Kategori");
            dtm.addColumn("Marka");
            dtm.addColumn("Stok");
            dtm.addColumn("Alis Fiyati");
            dtm.addColumn("Satış Fiyatı");
            dtm.addColumn("KDV ORANI");

            while (rs.next()) {
                dtm.addRow(new String[]{rs.getString("urunBarkod"), rs.getString("urunAdi"), rs.getString("urunKategori"), rs.getString("urunMarka"), rs.getString("urunStok"), rs.getString("urunAlisFiyati"),
                    rs.getString("urunSatisFiyati"), rs.getString("urunKDV")});
            }
            tblUrunler.setModel(dtm);

        } catch (Exception e) {
            System.err.println("okuma hatası...");
        } finally {
            db.dbKapat();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrunYonetimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrunYonetimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrunYonetimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrunYonetimiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrunYonetimiForm().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnDuzenle;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton btnStokEkle;
    private javax.swing.JButton btnStokEkle2;
    private javax.swing.JComboBox<String> cbAlisKdv;
    private javax.swing.JComboBox<String> cbKdvOrani;
    private javax.swing.JComboBox<String> cbSatisKdv;
    private javax.swing.JComboBox<String> cbUrunKategori;
    private javax.swing.JComboBox<String> cbUrunMarka;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUrunler;
    private javax.swing.JTextField txtAlisFiyati;
    private javax.swing.JTextField txtAra;
    private javax.swing.JTextField txtBarkod;
    private javax.swing.JTextField txtSatisFiyati;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtUrunAdi;
    // End of variables declaration//GEN-END:variables
}
